### ISSUE TITLE
Build Error on Ubuntu 22.04

### ISSUE THREAD

**Issue by gampUMKC** [Nuand/bladeRF-mac80211_hwsim#7]
Attempting to build on Ubuntu 22.04 with kernel version 6.2.0-33, I get this output from make -j4:

make -C /lib/modules/6.2.0-33-generic/build M=/home/test/wiphy-build/bladeRF-mac80211_hwsim modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/src/linux-headers-6.2.0-33-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.o
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c: In function ‘mac80211_hwsim_beacon_tx’:
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:1919:15: error: too few arguments to function ‘ieee80211_beacon_get’
 1919 |         skb = ieee80211_beacon_get(hw, vif);
      |               ^~~~~~~~~~~~~~~~~~~~
In file included from /home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:22:
./include/net/mac80211.h:5267:31: note: declared here
 5267 | static inline struct sk_buff *ieee80211_beacon_get(struct ieee80211_hw *hw,
      |                               ^~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/kernel.h:29,
                 from ./arch/x86/include/asm/percpu.h:27,
                 from ./arch/x86/include/asm/preempt.h:6,
                 from ./include/linux/preempt.h:78,
                 from ./include/linux/spinlock.h:56,
                 from ./include/linux/mmzone.h:8,
                 from ./include/linux/gfp.h:7,
                 from ./include/linux/slab.h:15,
                 from /home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:18:
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c: In function ‘mac80211_hwsim_bss_info_changed’:
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2132:31: error: ‘struct ieee80211_bss_conf’ has no member named ‘assoc’
 2132 |                           info->assoc, info->aid);
      |                               ^~
./include/linux/printk.h:429:33: note: in definition of macro ‘printk_index_wrap’
  429 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                                 ^~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:69:27: note: in expansion of macro ‘printk’
   69 | #define wiphy_dbg(x, ...) printk(__VA_ARGS__)
      |                           ^~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2131:17: note: in expansion of macro ‘wiphy_dbg’
 2131 |                 wiphy_dbg(hw->wiphy, "  ASSOC: assoc=%d aid=%d\n",
      |                 ^~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2132:44: error: ‘struct ieee80211_bss_conf’ has no member named ‘aid’
 2132 |                           info->assoc, info->aid);
      |                                            ^~
./include/linux/printk.h:429:33: note: in definition of macro ‘printk_index_wrap’
  429 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                                 ^~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:69:27: note: in expansion of macro ‘printk’
   69 | #define wiphy_dbg(x, ...) printk(__VA_ARGS__)
      |                           ^~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2131:17: note: in expansion of macro ‘wiphy_dbg’
 2131 |                 wiphy_dbg(hw->wiphy, "  ASSOC: assoc=%d aid=%d\n",
      |                 ^~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2133:33: error: ‘struct ieee80211_bss_conf’ has no member named ‘assoc’
 2133 |                 vp->assoc = info->assoc;
      |                                 ^~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2134:31: error: ‘struct ieee80211_bss_conf’ has no member named ‘aid’
 2134 |                 vp->aid = info->aid;
      |                               ^~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c: At top level:
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2815:29: error: initialization of ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u64)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, long long unsigned int)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u32)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, unsigned int)’} [-Werror=incompatible-pointer-types]
 2815 |         .bss_info_changed = mac80211_hwsim_bss_info_changed,    \
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2834:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2834 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2815:29: note: (near initialization for ‘mac80211_hwsim_ops.bss_info_changed’)
 2815 |         .bss_info_changed = mac80211_hwsim_bss_info_changed,    \
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2834:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2834 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2822:20: error: initialization of ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, unsigned int,  u16,  const struct ieee80211_tx_queue_params *)’ {aka ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, unsigned int,  short unsigned int,  const struct ieee80211_tx_queue_params *)’} from incompatible pointer type ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, u16,  const struct ieee80211_tx_queue_params *)’ {aka ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, short unsigned int,  const struct ieee80211_tx_queue_params *)’} [-Werror=incompatible-pointer-types]
 2822 |         .conf_tx = mac80211_hwsim_conf_tx,                      \
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2834:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2834 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2822:20: note: (near initialization for ‘mac80211_hwsim_ops.conf_tx’)
 2822 |         .conf_tx = mac80211_hwsim_conf_tx,                      \
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2834:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2834 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2815:29: error: initialization of ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u64)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, long long unsigned int)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u32)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, unsigned int)’} [-Werror=incompatible-pointer-types]
 2815 |         .bss_info_changed = mac80211_hwsim_bss_info_changed,    \
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2840:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2840 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2815:29: note: (near initialization for ‘mac80211_hwsim_mchan_ops.bss_info_changed’)
 2815 |         .bss_info_changed = mac80211_hwsim_bss_info_changed,    \
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2840:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2840 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2822:20: error: initialization of ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, unsigned int,  u16,  const struct ieee80211_tx_queue_params *)’ {aka ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, unsigned int,  short unsigned int,  const struct ieee80211_tx_queue_params *)’} from incompatible pointer type ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, u16,  const struct ieee80211_tx_queue_params *)’ {aka ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, short unsigned int,  const struct ieee80211_tx_queue_params *)’} [-Werror=incompatible-pointer-types]
 2822 |         .conf_tx = mac80211_hwsim_conf_tx,                      \
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2840:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2840 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2822:20: note: (near initialization for ‘mac80211_hwsim_mchan_ops.conf_tx’)
 2822 |         .conf_tx = mac80211_hwsim_conf_tx,                      \
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2840:9: note: in expansion of macro ‘HWSIM_COMMON_OPS’
 2840 |         HWSIM_COMMON_OPS
      |         ^~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2850:31: error: initialization of ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, struct ieee80211_chanctx_conf *)’ from incompatible pointer type ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_chanctx_conf *)’ [-Werror=incompatible-pointer-types]
 2850 |         .assign_vif_chanctx = mac80211_hwsim_assign_vif_chanctx,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2850:31: note: (near initialization for ‘mac80211_hwsim_mchan_ops.assign_vif_chanctx’)
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2851:33: error: initialization of ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, struct ieee80211_chanctx_conf *)’ from incompatible pointer type ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_chanctx_conf *)’ [-Werror=incompatible-pointer-types]
 2851 |         .unassign_vif_chanctx = mac80211_hwsim_unassign_vif_chanctx,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:2851:33: note: (near initialization for ‘mac80211_hwsim_mchan_ops.unassign_vif_chanctx’)
/home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.c:3022:41: error: ‘IEEE80211_EHT_MAC_CAP0_NSEP_PRIO_ACCESS’ undeclared here (not in a function); did you mean ‘IEEE80211_EHT_MAC_CAP0_EPCS_PRIO_ACCESS’?
 3022 |                                         IEEE80211_EHT_MAC_CAP0_NSEP_PRIO_ACCESS |
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         IEEE80211_EHT_MAC_CAP0_EPCS_PRIO_ACCESS
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:260: /home/test/wiphy-build/bladeRF-mac80211_hwsim/mac80211_hwsim.o] Error 1
make[1]: *** [Makefile:2026: /home/test/wiphy-build/bladeRF-mac80211_hwsim] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.2.0-33-generic'
make: *** [Makefile:4: all] Error 2

**Comment by Bl4ckbird28** [comment]
Hello @gampUMKC 
I wanted to ask if you were able to solve the problem? I currently have the same problem and can't get any further. Have you found a solution? If so, could you please let me know? 
Thanks in advance
